development:
  subdomain: ongraph-sandbox2
  api_key: qB6zspbSMprcZ2BrKGHmtq8sajciWnRzdZvpk6emGFk
  site_key: MpaPvXt7Kjqq1HFTLgsa4SKSoc7Q7UgdurzBuH3LQ
production:
  subdomain: flipout-web-development-sandbox
  api_key: AEivQVVTrzMCptA5dXqPoY9As9ozZQL3P5HJzCqfM8
  site_key: W7Z89pWQ1Iz4w7HIpp7JkZeE85Hhm2jDdZVwAU4NE4