# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7568ec9438c58047f54079e32953614a7317ed940cd37f7c3fa741b38b842d5cec5cf3a3758d7ea501a97b4789080d42b6e666a6812d6cf5632e4ea47235418c
  quandl_token: "akupyq38zWCZvjQhwLQH"
  quandl_url: "https://quandl.com/api/v3/datasets/"

test:
  secret_key_base: a00bd1400188c99a773ff5eac2bd281f5de3f6b4f3fdeb7398dfe9cae7a25b64a4544b724a318f9f1fc18c9874b745e9813c476e0dbe66ec233f3ff8919b1f7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
